// This file was generated by Prisma, and assumes you have installed the following:
import 'dotenv/config'; //import always from .env file
import { defineConfig } from 'prisma/config';
import { env } from './config/env.config';

export default defineConfig({
  schema: 'src/database/prisma/schema.prisma',
  migrations: {
    path: 'src/database/prisma/migrations',
  },
  datasource: {
    url: env.DATABASE_URL || '',
  },
});
